// Language translations - Global variable
window.TRANSLATIONS = {
    en: {
        title: 'MSP2 Tool - OBFX®',
        language: 'Language',
        zoom: 'Zoom',
        plan: 'Plan',
        obfxPro: 'OBFX Pro',
        autograph: 'Autograph',
        changePassword: 'Change Password',
        exit: 'Exit',
        welcomeTitle: 'Welcome to MSP2 Tool',
        welcomeSubtitle: 'Choose your login method',
        websocketLogin: 'WebSocket Login',
        accountLogin: 'Account Login',
        websocketPlaceholder: 'Paste WebSocket message here...',
        usernamePlaceholder: 'Username',
        passwordPlaceholder: 'Password',
        login: 'Login',
        loading: 'Loading...',
        querySent: 'Query sent...',
        approvedLogin: 'Approved Logging in...',
        banned: 'Banned!',
        bannedMessage: 'OBFX does not support login with this account',
        backToLogin: 'Back to Login',
        menu: 'Menu',
        changeMood: 'Change Mood',
        gender: 'Gender',
        gifts: 'Gifts',
        dailyTask: 'Daily Task',
        startEnhanced: 'Start Enhanced Daily Tasks',
        fastStart: 'Fast Start',
        applyMood: 'Apply Mood',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm New Password',
        cancel: 'Cancel',
        enterUsername: 'Enter username',
        findStart: 'Find & Start',
        stop: 'Stop',
        test: 'Test',
        totalFame: 'Total Fame:',
        close: 'Close',
        languageSelection: 'Language Selection',
        currentLanguage: 'Current Language:',
        zoomLevel: 'Zoom Level',
        selectRegion: 'Select Region',
        selectRegionDesc: 'Please select your region before logging in:',
        unitedStates: 'United States',
        europe: 'Europe',
        warning: 'Warning!',
        fastWarning1: 'Fast completion may lead to account suspension or ban.',
        startFastMode: 'Start Fast Mode',
        comments: 'Comments',
        noComments: 'No comments yet',
        status: 'Status',
        openAllGifts: 'Open All Gifts',
        sessionExpired: 'Session expired. Please login again.',
        tokenExpiring: 'Session will expire in 15 minutes.',
        loginSuccess: 'Login successful!',
        loginError: 'Login failed. Please check your credentials.',
        invalidCredentials: 'Invalid username or password.',
        connectionError: 'Connection error. Please try again.',
        friendsSettings: 'Friends Settings',
        friends: 'Friends',
        requestSenders: 'Request Senders',
        blocked: 'Blocked',
        deleteAll: 'Delete All',
        loadingFriends: 'Loading friends...',
        loadingRequests: 'Loading requests...',
        loadingBlocked: 'Loading blocked...',
        noFriends: 'No friends found',
        noRequests: 'No friend requests',
        noBlocked: 'No blocked users',
        level: 'Level',
        lastLogin: 'Last Login',
        remove: 'Remove',
        accept: 'Accept',
        reject: 'Reject',
        unblock: 'Unblock',
        dangerousAction: 'Dangerous Action!',
        deleteAllWarning: 'This action will remove ALL users from the selected category.',
        waitCountdown: 'Wait for countdown to finish...',
        yes: 'Yes',
        no: 'No',
        giftOpenSuccess: 'Gift opened successfully!',
        giftOpenError: 'Failed to open gift',
        giftOpening: 'Opening gift...',
        openingGifts: 'Opening gifts...',
        allGiftsOpened: 'All gifts opened successfully!',
        scammerTest: 'Scammer Test',
        securityStatus: 'Security Status',
        securitySafe: 'Safe',
        securitySuspicious: 'Suspicious',
        securityUnsafe: 'Unsafe',
        description: 'Description',
        loadingComments: 'Loading comments...',
        deletingComment: 'Deleting comment...',
        commentDeleted: 'Comment deleted successfully!',
        upgradeToObfxPlus: 'Upgrade to OBFX Plus',
        upgradeToObfxPro: 'Upgrade to OBFX Pro',
        requiresLevel10OrPlus: 'Requires Level 10+ or OBFX Plus',
        requiresObfxPro: 'Requires OBFX Pro subscription',
        planComparison: 'Plan Comparison',
        freePlan: 'Free Plan',
        plusPlan: 'OBFX Plus',
        proPlan: 'OBFX Pro',
        recommended: 'Recommended',
        dailyTasksLevel10: 'Daily Tasks (Level 10+)',
        limitedMoods: 'Limited Moods (7)',
        noGifts: 'No Gifts Access',
        friendsManagement: 'Friends Management',
        unlimitedDailyTasks: 'Unlimited Daily Tasks',
        allMoods: 'All Moods (37)',
        giftsAccess: 'Full Gifts Access',
        advancedFriends: 'Advanced Friends',
        prioritySupport: 'Priority Support',
        fastFeatures: 'Fast Features',
        multiAccount: 'Multi-Account Management',
        bulkOperations: 'Bulk Operations',
        vipOnly: 'VIP Only',
        passwordChangeSuccess: 'Password changed successfully!',
        downloadAccountFile: 'Would you like to download your account file?',
        noThanks: 'No, thanks',
        whatsThis: 'What\'s this for?',
        yesRecommended: 'Yes (recommended)',
        accountFileInfo: 'Your account file contains your updated credentials. We recommend downloading and storing it securely as a backup. This file can help you recover your account if you forget your login details.',
        accountFileInfoTitle: 'Account File Information',
        passwordChanging: 'Changing password...',
        passwordChangeError: 'Failed to change password',
        passwordMismatch: 'Passwords do not match',
        passwordTooShort: 'Password must be at least 6 characters',
        fillAllFields: 'Please fill all fields',
        passwordSaving: 'Saving password...',
        downloadStarted: 'Account file download started',
        currentPasswordWrong: 'Current password is incorrect',
        accountManagement: 'Account Management',
        accountInfo: 'Account Info',
        accountMethod: 'Account Method',
        websocketMethod: 'WebSocket Method',
        save: 'Save',
        reset: 'Reset',
        accounts: 'Accounts',
        normalTasks: 'Normal Daily Tasks',
        fastTasks: 'Fast Daily Tasks',
        accountSaved: 'Account saved successfully!',
        accountsReset: 'All accounts reset!',
        processingAccounts: 'Processing accounts...',
        accountsProcessed: 'All accounts processed!',
        specialFriends: 'Special Friends',
        lastLoginDate: 'Last Login Date',
        currentLocation: 'Current Location'
    },
    tr: {
        title: 'MSP2 Aracı - OBFX®',
        language: 'Dil',
        zoom: 'Yakınlaştır',
        plan: 'Plan',
        obfxPro: 'OBFX Pro',
        autograph: 'İmza',
        changePassword: 'Şifre Değiştir',
        exit: 'Çıkış',
        welcomeTitle: 'MSP2 Aracına Hoş Geldiniz',
        welcomeSubtitle: 'Giriş yönteminizi seçin',
        websocketLogin: 'WebSocket Girişi',
        accountLogin: 'Hesap Girişi',
        websocketPlaceholder: 'WebSocket mesajını buraya yapıştırın...',
        usernamePlaceholder: 'Kullanıcı Adı',
        passwordPlaceholder: 'Şifre',
        login: 'Giriş Yap',
        loading: 'Yükleniyor...',
        querySent: 'Sorgu gönderildi...',
        approvedLogin: 'Onaylandı, giriş yapılıyor...',
        banned: 'Yasaklandınız!',
        bannedMessage: 'OBFX bu hesabı giriş yapmasını desteklemiyor',
        backToLogin: 'Giriş Ekranına Dön',
        menu: 'Menü',
        changeMood: 'Ruh Hali Değiştir',
        gender: 'Cinsiyet',
        gifts: 'Hediyeler',
        dailyTask: 'Günlük Görev',
        startEnhanced: 'Gelişmiş Günlük Görevleri Başlat',
        fastStart: 'Hızlı Başlat',
        applyMood: 'Ruh Halini Uygula',
        currentPassword: 'Mevcut Şifre',
        newPassword: 'Yeni Şifre',
        confirmPassword: 'Yeni Şifreyi Onayla',
        cancel: 'İptal',
        enterUsername: 'Kullanıcı adını girin',
        findStart: 'Bul ve Başlat',
        stop: 'Durdur',
        test: 'Test',
        totalFame: 'Toplam Şöhret:',
        close: 'Kapat',
        languageSelection: 'Dil Seçimi',
        currentLanguage: 'Mevcut Dil:',
        zoomLevel: 'Yakınlaştırma Seviyesi',
        selectRegion: 'Bölge Seç',
        selectRegionDesc: 'Giriş yapmadan önce lütfen bölgenizi seçin:',
        unitedStates: 'Amerika Birleşik Devletleri',
        europe: 'Avrupa',
        warning: 'Uyarı!',
        fastWarning1: 'Hızlı tamamlama hesap askıya alınmasına neden olabilir.',
        startFastMode: 'Hızlı Modu Başlat',
        comments: 'Yorumlar',
        noComments: 'Henüz yorum yok',
        status: 'Durum',
        openAllGifts: 'Tüm Hediyeleri Aç',
        sessionExpired: 'Oturum süresi doldu. Lütfen tekrar giriş yapın.',
        tokenExpiring: 'Oturum 15 dakika içinde sona erecek.',
        loginSuccess: 'Giriş başarılı!',
        loginError: 'Giriş başarısız. Lütfen bilgilerinizi kontrol edin.',
        invalidCredentials: 'Geçersiz kullanıcı adı veya şifre.',
        connectionError: 'Bağlantı hatası. Lütfen tekrar deneyin.',
        friendsSettings: 'Arkadaş Ayarları',
        friends: 'Arkadaşlar',
        requestSenders: 'İstek Gönderenler',
        blocked: 'Engellenenler',
        deleteAll: 'Tümünü Sil',
        loadingFriends: 'Arkadaşlar yükleniyor...',
        loadingRequests: 'İstekler yükleniyor...',
        loadingBlocked: 'Engellenenler yükleniyor...',
        noFriends: 'Arkadaş bulunamadı',
        noRequests: 'Arkadaşlık isteği yok',
        noBlocked: 'Engellenen kullanıcı yok',
        level: 'Seviye',
        lastLogin: 'Son Giriş',
        remove: 'Kaldır',
        accept: 'Kabul Et',
        reject: 'Reddet',
        unblock: 'Engeli Kaldır',
        dangerousAction: 'Tehlikeli Eylem!',
        deleteAllWarning: 'Bu eylem seçilen kategorideki TÜM kullanıcıları kaldıracak.',
        waitCountdown: 'Geri sayımın bitmesini bekleyin...',
        yes: 'Evet',
        no: 'Hayır',
        giftOpenSuccess: 'Hediye başarıyla açıldı!',
        giftOpenError: 'Hediye açılamadı',
        giftOpening: 'Hediye açılıyor...',
        openingGifts: 'Hediyeler açılıyor...',
        allGiftsOpened: 'Tüm hediyeler başarıyla açıldı!',
        scammerTest: 'Dolandırıcı Testi',
        securityStatus: 'Güvenlik Durumu',
        securitySafe: 'Güvenli',
        securitySuspicious: 'Şüpheli',
        securityUnsafe: 'Güvenli Değil',
        description: 'Açıklama',
        loadingComments: 'Yorumlar yükleniyor...',
        deletingComment: 'Yorum siliniyor...',
        commentDeleted: 'Yorum başarıyla silindi!',
        upgradeToObfxPlus: 'OBFX Plus\'a Yükselt',
        upgradeToObfxPro: 'OBFX Pro\'ya Yükselt',
        requiresLevel10OrPlus: 'Seviye 10+ veya OBFX Plus gerektirir',
        requiresObfxPro: 'OBFX Pro aboneliği gerektirir',
        planComparison: 'Plan Karşılaştırması',
        freePlan: 'Ücretsiz Plan',
        plusPlan: 'OBFX Plus',
        proPlan: 'OBFX Pro',
        recommended: 'Önerilen',
        dailyTasksLevel10: 'Günlük Görevler (Seviye 10+)',
        limitedMoods: 'Sınırlı Ruh Halleri (7)',
        noGifts: 'Hediye Erişimi Yok',
        friendsManagement: 'Arkadaş Yönetimi',
        unlimitedDailyTasks: 'Sınırsız Günlük Görevler',
        allMoods: 'Tüm Ruh Halleri (37)',
        giftsAccess: 'Tam Hediye Erişimi',
        advancedFriends: 'Gelişmiş Arkadaş Özellikleri',
        prioritySupport: 'Öncelikli Destek',
        fastFeatures: 'Hızlı Özellikler',
        multiAccount: 'Çoklu Hesap Yönetimi',
        bulkOperations: 'Toplu İşlemler',
        vipOnly: 'Sadece VIP',
        passwordChangeSuccess: 'Şifre başarıyla değiştirildi!',
        downloadAccountFile: 'Hesap dosyasını indirmek ister misiniz?',
        noThanks: 'Hayır, teşekkürler',
        whatsThis: 'Bu ne işe yarıyor?',
        yesRecommended: 'Evet (önerilir)',
        accountFileInfo: 'Hesap dosyası güncellenmiş kimlik bilgilerinizi içerir. Yedek olarak güvenli bir yerde saklamanızı öneriyoruz. Bu dosya, giriş bilgilerinizi unutursanız hesabınızı kurtarmanıza yardımcı olabilir.',
        accountFileInfoTitle: 'Hesap Dosyası Bilgisi',
        passwordChanging: 'Şifre değiştiriliyor...',
        passwordChangeError: 'Şifre değiştirilemedi',
        passwordMismatch: 'Şifreler eşleşmiyor',
        passwordTooShort: 'Şifre en az 6 karakter olmalıdır',
        fillAllFields: 'Lütfen tüm alanları doldurun',
        passwordSaving: 'Şifre kaydediliyor...',
        downloadStarted: 'Hesap dosyası indirimi başladı',
        currentPasswordWrong: 'Mevcut şifre yanlış',
        accountManagement: 'Hesap Yönetimi',
        accountInfo: 'Hesap Bilgileri',
        accountMethod: 'Hesap Yöntemi',
        websocketMethod: 'WebSocket Yöntemi',
        save: 'Kaydet',
        reset: 'Sıfırla',
        accounts: 'Hesaplar',
        normalTasks: 'Normal Günlük Görevler',
        fastTasks: 'Hızlı Günlük Görevler',
        accountSaved: 'Hesap başarıyla kaydedildi!',
        accountsReset: 'Tüm hesaplar sıfırlandı!',
        processingAccounts: 'Hesaplar işleniyor...',
        accountsProcessed: 'Tüm hesaplar işlendi!',
        specialFriends: 'Özel Arkadaşlar',
        lastLoginDate: 'Son Giriş Tarihi',
        currentLocation: 'Mevcut Konum'
    },
    az: {
        title: 'MSP2 Aləti - OBFX®',
        language: 'Dil',
        zoom: 'Yaxınlaşdırma',
        plan: 'Plan',
        obfxPro: 'OBFX Pro',
        autograph: 'İmza',
        changePassword: 'Şifrəni Dəyiş',
        exit: 'Çıxış',
        welcomeTitle: 'MSP2 Alətinə Xoş Gəldiniz',
        welcomeSubtitle: 'Giriş üsulunuzu seçin',
        websocketLogin: 'WebSocket Girişi',
        accountLogin: 'Hesab Girişi',
        websocketPlaceholder: 'WebSocket mesajını bura yapışdırın...',
        usernamePlaceholder: 'İstifadəçi Adı',
        passwordPlaceholder: 'Şifrə',
        login: 'Giriş',
        loading: 'Yüklənir...',
        querySent: 'Sorğu göndərildi...',
        approvedLogin: 'Təsdiqləndi, giriş edilir...',
        banned: 'Qadağan edildiniz!',
        bannedMessage: 'OBFX bu hesabla girişi dəstəkləmir',
        backToLogin: 'Giriş Ekranına Qayıt',
        menu: 'Menyu',
        changeMood: 'Əhval-Ruhiyyəni Dəyiş',
        gender: 'Cins',
        gifts: 'Hədiyyələr',
        dailyTask: 'Gündəlik Tapşırıq',
        startEnhanced: 'Təkmilləşdirilmiş Gündəlik Tapşırıqları Başlat',
        fastStart: 'Sürətli Başlat',
        applyMood: 'Əhval-Ruhiyyəni Tətbiq Et',
        currentPassword: 'Mövcud Şifrə',
        newPassword: 'Yeni Şifrə',
        confirmPassword: 'Yeni Şifrəni Təstiq Et',
        cancel: 'Ləğv Et',
        enterUsername: 'İstifadəçi adını daxil edin',
        findStart: 'Tap və Başlat',
        stop: 'Dayandır',
        test: 'Test',
        totalFame: 'Ümumi Şöhrət:',
        close: 'Bağla',
        languageSelection: 'Dil Seçimi',
        currentLanguage: 'Mövcud Dil:',
        zoomLevel: 'Yaxınlaşdırma Səviyyəsi',
        selectRegion: 'Region Seç',
        selectRegionDesc: 'Giriş etməzdən əvvəl regionunuzu seçin:',
        unitedStates: 'Amerika Birləşmiş Ştatları',
        europe: 'Avropa',
        warning: 'Xəbərdarlıq!',
        fastWarning1: 'Sürətli tamamlama hesabın askıya alınmasına səbəb ola bilər.',
        startFastMode: 'Sürətli Rejimi Başlat',
        comments: 'Şərhlər',
        noComments: 'Hələ şərh yoxdur',
        status: 'Vəziyyət',
        openAllGifts: 'Bütün Hədiyyələri Aç',
        sessionExpired: 'Sessiya müddəti bitdi. Təkrar giriş edin.',
        tokenExpiring: 'Sessiya 15 dəqiqədə sona çatacaq.',
        loginSuccess: 'Giriş uğurlu oldu!',
        loginError: 'Giriş uğursuz. Məlumatlarınızı yoxlayın.',
        invalidCredentials: 'Yanlış istifadəçi adı və ya şifrə.',
        connectionError: 'Bağlantı xətası. Təkrar cəhd edin.',
        friendsSettings: 'Dost Parametrləri',
        friends: 'Dostlar',
        requestSenders: 'İstək Göndərənlər',
        blocked: 'Əngəllənmiş',
        deleteAll: 'Hamısını Sil',
        loadingFriends: 'Dostlar yüklənir...',
        loadingRequests: 'İstəklər yüklənir...',
        loadingBlocked: 'Əngəllənmişlər yüklənir...',
        noFriends: 'Dost tapılmadı',
        noRequests: 'Dostluq istəyi yoxdur',
        noBlocked: 'Əngəllənmiş istifadəçi yoxdur',
        level: 'Səviyyə',
        lastLogin: 'Son Giriş',
        remove: 'Sil',
        accept: 'Qəbul Et',
        reject: 'Rədd Et',
        unblock: 'Əngəli Götür',
        dangerousAction: 'Təhlükəli Əməliyyat!',
        deleteAllWarning: 'Bu əməliyyat seçilən kateqoriyadakı BÜTÜN istifadəçiləri siləcək.',
        waitCountdown: 'Geri sayımın bitməsini gözləyin...',
        yes: 'Bəli',
        no: 'Xeyr',
        giftOpenSuccess: 'Hədiyyə uğurla açıldı!',
        giftOpenError: 'Hədiyyə açılmadı',
        giftOpening: 'Hədiyyə açılır...',
        openingGifts: 'Hədiyyələr açılır...',
        allGiftsOpened: 'Bütün hədiyyələr uğurla açıldı!',
        scammerTest: 'Fırıldaqçı Testi',
        securityStatus: 'Təhlükəsizlik Vəziyyəti',
        securitySafe: 'Təhlükəsiz',
        securitySuspicious: 'Şübhəli',
        securityUnsafe: 'Təhlükəsiz Deyil',
        description: 'Təsvir',
        loadingComments: 'Şərhlər yüklənir...',
        deletingComment: 'Şərh silinir...',
        commentDeleted: 'Şərh uğurla silindi!',
        upgradeToObfxPlus: 'OBFX Plus-a Yüksəlt',
        upgradeToObfxPro: 'OBFX Pro-ya Yüksəlt',
        requiresLevel10OrPlus: 'Səviyyə 10+ və ya OBFX Plus tələb edir',
        requiresObfxPro: 'OBFX Pro abunəliyi tələb edir',
        planComparison: 'Plan Müqayisəsi',
        freePlan: 'Pulsuz Plan',
        plusPlan: 'OBFX Plus',
        proPlan: 'OBFX Pro',
        recommended: 'Tövsiyə olunur',
        dailyTasksLevel10: 'Gündəlik Tapşırıqlar (Səviyyə 10+)',
        limitedMoods: 'Məhdud Əhval-Ruhiyyələr (7)',
        noGifts: 'Hədiyyə Girişi Yoxdur',
        friendsManagement: 'Dost İdarəetməsi',
        unlimitedDailyTasks: 'Məhdudiyyətsiz Gündəlik Tapşırıqlar',
        allMoods: 'Bütün Əhval-Ruhiyyələr (37)',
        giftsAccess: 'Tam Hədiyyə Girişi',
        advancedFriends: 'Təkmil Dost Xüsusiyyətləri',
        prioritySupport: 'Prioritet Dəstəyi',
        fastFeatures: 'Sürətli Xüsusiyyətlər',
        multiAccount: 'Çoxlu Hesab İdarəetməsi',
        bulkOperations: 'Toplu Əməliyyatlar',
        vipOnly: 'Yalnız VIP',
        passwordChangeSuccess: 'Şifrə uğurla dəyişdirildi!',
        downloadAccountFile: 'Hesab faylını yükləmək istəyirsiniz?',
        noThanks: 'Xeyr, təşəkkür edirəm',
        whatsThis: 'Bu nə üçündür?',
        yesRecommended: 'Bəli (tövsiyə olunur)',
        accountFileInfo: 'Hesab faylı yenilənmiş giriş məlumatlarınızı ehtiva edir. Ehtiyat olaraq təhlükəsiz yerdə saxlamağı tövsiyə edirik. Bu fayl giriş məlumatlarınızı unutsanız hesabınızı bərpa etməyə kömək edə bilər.',
        accountFileInfoTitle: 'Hesab Faylı Məlumatı',
        passwordChanging: 'Şifrə dəyişdirilir...',
        passwordChangeError: 'Şifrə dəyişdirilə bilmədi',
        passwordMismatch: 'Şifrələr uyğun gəlmir',
        passwordTooShort: 'Şifrə ən az 6 simvol olmalıdır',
        fillAllFields: 'Bütün sahələri doldurun',
        passwordSaving: 'Şifrə yadda saxlanılır...',
        downloadStarted: 'Hesab faylı yüklənməsi başladı',
        currentPasswordWrong: 'Mövcud şifrə səhvdir',
        accountManagement: 'Hesab İdarəetməsi',
        accountInfo: 'Hesab Məlumatları',
        accountMethod: 'Hesab Üsulu',
        websocketMethod: 'WebSocket Üsulu',
        save: 'Saxla',
        reset: 'Sıfırla',
        accounts: 'Hesablar',
        normalTasks: 'Normal Gündəlik Tapşırıqlar',
        fastTasks: 'Sürətli Gündəlik Tapşırıqlar',
        accountSaved: 'Hesab uğurla saxlanıldı!',
        accountsReset: 'Bütün hesablar sıfırlandı!',
        processingAccounts: 'Hesablar emal olunur...',
        accountsProcessed: 'Bütün hesablar emal olundu!',
        specialFriends: 'Xüsusi Dostlar',
        lastLoginDate: 'Son Giriş Tarixi',
        currentLocation: 'Hazırki Məkan'
    }
};

// Console log to verify loading
console.log('Language.js loaded successfully!', window.TRANSLATIONS ? 'Translations available' : 'Translations missing');
